export const FIND_ADDRESS_BY_ID_REQUEST = "FIND_ADDRESS_BY_ID_REQUEST"
export const FIND_ADDRESS_BY_ID_SUCCESS = "FIND_ADDRESS_BY_ID_SUCCESS"
export const FIND_ADDRESS_BY_ID_FAILURE = "FIND_ADDRESS_BY_ID_FAILURE"